@startuml
'https://plantuml.com/class-diagram


class LocationHelper{
-LocationClient locationClient
+BDLocation curLocation
-MutableList listenerList
-BDAbstractLocationListener locationListener
+start()
+stop()
+addLocationListener(listener: (BDLocation) -> Unit)
+removeLocationListener(listener: (BDLocation) -> Unit)
-logLocationInfo(locType: Int)
}


@enduml